# 
# CALCULATOR-PS2 KEYBOARD- ECOMP PROJECT
# JOÃO CARDOSO- PEDRO FERREIRA
#	Calculator
#
	
Waiting 
	rdw PS2_BASE
	nop
	nop
	wrw DISPLAY_BASE
	nop
	nop
	beqi Waiting
	nop
	nop
	wrw R2 # Write Code to R2, START code recognition!
	addi -112 # 0 Code
	beqi Load
	ldi 0
	nop
	rdw R2
	addi -105 # 1 Code
	beqi Load
	ldi 1
	nop
	rdw R2
	addi -114 # 2 Code
	beqi Load
	ldi 2
	nop
	rdw R2
	addi -122 # 3 Code
	beqi Load
	ldi 3
	nop
	addi -107 # 4 Code
	beqi Load
	ldi 4
	nop
	addi -115 # 5 Code
	beqi Load
	ldi 5
	nop
	addi -116 # 6 Code
	beqi Load
	ldi 6
	nop
	addi -108 # 7 Code
	beqi Load
	ldi 7
	nop
	addi -117 # 8 Code
	beqi Load
	ldi 8
	nop
	addi -125 # 9 Code
	beqi Load
	ldi 9
	nop
	bneqi Waiting
	nop
	nop # End of Code recognition! Code not valuable!
Load 
	wrw R3
	wrw DISPLAY_BASE
	ldi 0
	beqi Waiting 
	nop
	nop



#finish program by jumping back to boot ROM
	ldi 0
	beqi PROG_ROM
	nop
	
# PS2_BASE-> x025
# DONE -> x026

# char ascii constants placed here	
c0	.memset 0x0A
	.memset 0x48
	.memset 0x65
	.memset 0x6C
	.memset 0x6C
	.memset 0x6F
	.memset 0x20
	.memset 0x77
	.memset 0x6F
	.memset 0x72
	.memset 0x6C
	.memset 0x64
	.memset 0x21
	.memset 0x0A
	.memset 0x0D
	.memset 0x0A












