# 
# CALCULATOR-PS2 KEYBOARD- ECOMP PROJECT
# JOÃO CARDOSO- PEDRO FERREIRA
#	Calculator
#

Waiting	    ldi 0
            ldi 0
		    wrw R1
		    wrw R2
		    wrw R3
		    wrw R4
		    wrw R5
		    wrw R6
		    wrw R7
		    wrw R8
		    wrw R9
		    wrw R10
		    wrw R11
		    wrw R12
		    wrw R13
		    wrw R14
		    wrw R15
		    rdw PS2_BASE
		    nop
		    nop
		    wrw DISPLAY_BASE
		    nop
		    nop
		    beqi Waiting
		    nop
		    nop
Load 	    wrw R3
            wrw R3
		    wrw DISPLAY_BASE
		    ldi R4
		    addi 1
        

#finish program by jumping back to boot ROM
	ldi 0
	beqi PROG_ROM
	nop
	
# PS2_BASE-> x025
# DONE -> x026

# char ascii constants placed here	
c0	.memset 0x0A
	.memset 0x48
	.memset 0x65
	.memset 0x6C
	.memset 0x6C
	.memset 0x6F
	.memset 0x20
	.memset 0x77
	.memset 0x6F
	.memset 0x72
	.memset 0x6C
	.memset 0x64
	.memset 0x21
	.memset 0x0A
	.memset 0x0D
	.memset 0x0A












