# 
# CALCULATOR-PS2 KEYBOARD- ECOMP PROJECT
# JOÃO CARDOSO- PEDRO FERREIRA
#	Calculator
#	
Wai     nop
	    nop
        rdw PS2_BASE
#PS2 BASE 3
        wrw R4
        beqi Wai
        nop
        nop
        rdw R4
	    wrw DISPLAY_BASE
        nop
        ldi 1
	    bneqi Wai
        nop
        nop
        ldi 0
        beqi Wai
        nop
        nop
Wait     nop
	    nop
        rdw 0x31 
#PS2 BASE 2
        wrw R4
        beqi Wait
        nop
        nop
        rdw R4
	    wrw DISPLAY_BASE
        nop
        ldi 1
	    bneqi Wait
        nop
        nop
        ldi 0
        beqi Wait
        nop
        nop
Waitt   nop
	    nop
        rdw 0x32
#PS2 BASE 3
        wrw R4
        beqi Wai
        nop
        nop
        rdw R4
	    wrw DISPLAY_BASE
        nop
        ldi 1
	    bneqi Waitt
        nop
        nop
        ldi 0
        beqi Waitt
        nop
        nop




#finish program by jumping back to boot ROM
	ldi 0
	beqi PROG_ROM
	nop
    nop
    
	
# PS2_BASE-> x025
# DONE -> x026












