# 
# CALCULATOR-PS2 KEYBOARD- ECOMP PROJECT
# JOÃO CARDOSO- PEDRO FERREIRA
#	Calculator
#	
Wai     nop
	    nop
        rdw PS2_BASE
        nop
        nop
        nop
        wrw R4
        nop
        nop
        nop
#        wrw DISPLAY_BASE
        nop
        beqi Wai
        nop
        nop
        rdw R4
        nop
        nop
	    wrw DISPLAY_BASE
        nop
        nop
        ldi 1
	    bneqi Wai
        nop
        nop
        ldi 0
        beqi Wai




#finish program by jumping back to boot ROM
#	ldi 1
#	beqi PROG_RAM
#	nop
#   nop
    
	
# PS2_BASE-> x025
# DONE -> x026












